import install from "../src/components";
export { default as VTextFieldMoney } from "../src/components/Decimal.vue";
export { default as VTextFieldPercent } from "../src/components/Decimal.vue";
export { default as VTextFieldInteger } from "../src/components/Integer.vue";
export { default as VTextFieldDateTime } from "../src/components/DateTime.vue";
//export {default as VTextField DateTimePicker} from "../src/components/DateTimePicker.vue";
export { default as VTextFieldSimpleMask } from "../src/components/SimpleMask.vue";
export { default as VTextFieldCpf } from "../src/components/Cpf.vue";
export { default as VTextFieldCnpj } from "../src/components/Cnpj.vue";
export { default as VTextFieldCep } from "../src/components/Cep.vue";
export { default as VTextFieldFileBase64 } from "../src/components/FileBase64.vue";
export { default as VTextFieldDotNumber } from "../src/components/DotNumber.vue";
export default install;
